export const navnListe = [
    { name: "Burt"},
    { name: "Misjonærene"},
    { name: "Astroza"},
    { name: "Tupas"},
    { name: "E. D. Horgmo"},
    { name: "Jensen"},
    { name: "Doris P."},
    { name: "T. Carlsen"},
    { name: "Barsisa"},
    { name: "Prakash"},
    { name: "Muren familien"},
    { name: "Austenaa"},
    { name: "Austenaa familien"},
    { name: "Rikheim Kofstad"},
    { name: "S. Isaksen"},
    { name: "Tapia"},
    { name: "Jørgensen"},
    { name: "Skovly"},
    { name: "J. & E-K Edvardsen"},
    { name: "M. Sørensen"},
    { name: "J. Andersen"},
    { name: "M. Andersen"},
    { name: "Høgset"},
    { name: "Porsbøll"},
    { name: "da Costa"},
    { name: "J. Brekke"},
    { name: "Røsaker"},
    { name: "L. A. Andersen"},
    { name: "Jacobsen"},
    { name: "Svanevik"},
    { name: "Dalere"},
    { name: "Galiza"},
    { name: "M  & Y. Olsen"},
    { name: "UK/UM v/S.M. Arias"},
    { name: "Amundsen"},
    { name: "Clement"},
    { name: "R. Andersen"},
    { name: ". Andersen"},
    { name: "Lindstad"},
    { name: "Moe"},
    { name: "Aabo"},
    { name: "Arias"},
    { name: "Fox"},
    { name: "Svendsen"},
    { name: "I. Andersen"},
    { name: "Monsalve"},
    { name: "Capizzi"},
    { name: "Delalić"},
    { name: "M. Amundsen"},
    { name: "Herheim"},
    { name: "Agreda"},
    { name: "Hojem"},
    { name: "Kerr"},
    { name: "Rosenkilde"},
    { name: "Vasquez"},
    { name: "M. Herland"},
    { name: "T-A. Herland"},
    { name: "H. Herland"},
    { name: "Wang"},
    { name: "Heistø Carlsen"},
    { name: "Packer family"},
    { name: "Edvardsen"},
    { name: "Weli familien (Weli family)"},
    { name: "Eng"},
    { name: "Judson"},
    { name: "R. Riksheim"},
    { name: "Sande"},
    { name: "Daimin"},
    { name: "M. Gabrielsen"},
    { name: "Noen/somebody"},
    { name: "Er det noen flere som kan stille?"},
]